services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432" # Allows you to connect via pgAdmin/DBeaver from your LAN if needed
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - /app/.venv # Protects the container's venv from being overwritten by the host
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=django_db
      - DB_USER=django_user
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: