# Generated by Django 6.0.4 on 2026-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_alter_note_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
