# Generated by Django 6.0.4 on 2026-07-15 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farm_photos/')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Name or Address')),
                ('users', models.ManyToManyField(related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('reportablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.reportablemodel')),
                ('animal_naming_schema', models.CharField(choices=[('IC', '<Animal Number> - <Animal Category>'), ('AN', '<Animal Name>'), ('BI', '<Animal Breed> - <Animal Number>')], default='IC', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('portal.reportablemodel',),
        ),
        migrations.AddField(
            model_name='reportablemodel',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_groups', to='portal.farm'),
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_templates', to='portal.farm')),
            ],
            options={
                'unique_together': {('slug', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='LivestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('report_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.reportablemodel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.recordtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('reportablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.reportablemodel')),
                ('category', models.CharField(choices=[('MC', 'Market Chicken'), ('EC', 'Exhibition Chicken'), ('ED', 'Exhibition Duck'), ('MD', 'Market Duck'), ('EG', 'Exhibition Goose'), ('MG', 'Market Goose'), ('ET', 'Exhibition Turkey'), ('MT', 'Market Turkey'), ('HGF', 'Helmeted Guinea Fowl'), ('BS', 'Breeding Swine'), ('MH', 'Market Hog'), ('MB', 'Market Beef'), ('MBF', 'Beef, Feeder'), ('MDF', 'Dairy Beef Feeder'), ('BB', 'Beef, Breeder'), ('RB', 'Rabbit, Breeder'), ('MR', 'Market Rabbit'), ('RP', 'Pet Rabbit'), ('DCF', 'Dairy Calf'), ('DYH', 'Dairy Yearling Heifer'), ('DC', 'Dairy Cow'), ('DG', 'Dairy Goat'), ('MG', 'Market Goat'), ('SG', 'Specialty Goat'), ('HO', 'Horse'), ('LA', 'Llama'), ('AL', 'Alpaca'), ('ML', 'Market Lamb'), ('BS', 'Breed Sheep')], max_length=3)),
                ('breed', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth (Priority over age value)')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1, null=True)),
                ('tag_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='Tag UUID')),
                ('group_index', models.SmallIntegerField(verbose_name="The animal's id within its group")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='portal.animalgroup', verbose_name='Belongs to group: ')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'group_index'), name='unique_index_within_group')],
            },
            bases=('portal.reportablemodel',),
        ),
    ]
