# Generated by Django 6.0.4 on 2026-07-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockrecord',
            name='report_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='portal.reportablemodel'),
        ),
    ]
