# Generated by Django 6.0.4 on 2026-06-20 00:38

import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_templates', to='portal.farm')),
            ],
            options={
                'unique_together': {('slug', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='LivestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('report_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.reportablemodel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.recordtemplate')),
            ],
        ),
    ]
