# Generated by Django 6.0.4 on 2026-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_livestockrecord_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livestockrecord',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
