# Generated by Django 6.0.4 on 2026-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_livestockrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livestockrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
