# Generated by Django 6.0.4 on 2026-06-21 16:49

import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_animal_public_id_alter_animalgroup_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalgroup',
            name='farm',
        ),
        migrations.AddField(
            model_name='reportablemodel',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='animal_groups', to='portal.farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
