# Generated by Django 6.0.4 on 2026-07-02 02:07

import django_extensions.db.fields
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_animalgroup_farm_reportablemodel_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockrecord',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recordtemplate',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
