# Generated by Django 6.0.4 on 2026-07-02 02:09

import django_extensions.db.fields
import shortuuid.main
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_livestockrecord_public_id_alter_animal_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
