# Generated by Django 6.0.4 on 2026-07-12 21:15

import django_extensions.db.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_animal_public_id_alter_animalgroup_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='public_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
