# Generated by Django 6.0.4 on 2026-04-16 17:14

import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "public_id",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "public_id",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "animal_naming_schema",
                    models.CharField(
                        choices=[
                            ("IC", "<Animal Number> - <Animal Category>"),
                            ("AN", "<Animal Name>"),
                            ("BI", "<Animal Breed> - <Animal Number>"),
                        ],
                        default="IC",
                        max_length=2,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animal_groups",
                        to="management.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MC", "Market Chicken"),
                            ("EC", "Exhibition Chicken"),
                            ("ED", "Exhibition Duck"),
                            ("MD", "Market Duck"),
                            ("EG", "Exhibition Goose"),
                            ("MG", "Market Goose"),
                            ("ET", "Exhibition Turkey"),
                            ("MT", "Market Turkey"),
                            ("HGF", "Helmeted Guinea Fowl"),
                            ("BS", "Breeding Swine"),
                            ("MH", "Market Hog"),
                            ("MB", "Market Beef"),
                            ("MBF", "Beef, Feeder"),
                            ("MDF", "Dairy Beef Feeder"),
                            ("BB", "Beef, Breeder"),
                            ("RB", "Rabbit, Breeder"),
                            ("MR", "Market Rabbit"),
                            ("RP", "Pet Rabbit"),
                            ("DCF", "Dairy Calf"),
                            ("DYH", "Dairy Yearling Heifer"),
                            ("DC", "Dairy Cow"),
                            ("DG", "Dairy Goat"),
                            ("MG", "Market Goat"),
                            ("SG", "Specialty Goat"),
                            ("HO", "Horse"),
                            ("LA", "Llama"),
                            ("AL", "Alpaca"),
                            ("ML", "Market Lamb"),
                            ("BS", "Breed Sheep"),
                        ],
                        max_length=3,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tag_id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="Tag UUID",
                    ),
                ),
                ("group_index", models.SmallIntegerField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="management.animalgroup",
                        verbose_name="Belongs to group: ",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "group_index"),
                        name="unique_index_within_group",
                    )
                ],
            },
        ),
    ]
