# Generated by Django 6.0.4 on 2026-04-13 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MC', 'Market Chicken'), ('EC', 'Exhibition Chicken'), ('ED', 'Exhibition Duck'), ('MD', 'Market Duck'), ('EG', 'Exhibition Goose'), ('MG', 'Market Goose'), ('ET', 'Exhibition Turkey'), ('MT', 'Market Turkey'), ('HGF', 'Helmeted Guinea Fowl'), ('BS', 'Breeding Swine'), ('MH', 'Market Hog'), ('MB', 'Market Beef'), ('MBF', 'Beef, Feeder'), ('MDF', 'Dairy Beef Feeder'), ('BB', 'Beef, Breeder'), ('RB', 'Rabbit, Breeder'), ('MR', 'Market Rabbit'), ('RP', 'Pet Rabbit'), ('DCF', 'Dairy Calf'), ('DYH', 'Dairy Yearling Heifer'), ('DC', 'Dairy Cow'), ('DG', 'Dairy Goat'), ('MG', 'Market Goat'), ('SG', 'Specialty Goat'), ('HO', 'Horse'), ('LA', 'Llama'), ('AL', 'Alpaca'), ('ML', 'Market Lamb'), ('BS', 'Breed Sheep')], max_length=3)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_id', models.UUIDField(null=True, unique=True, verbose_name='Tag UUID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='management.animalgroup', verbose_name='Belongs to group: ')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animalgroup',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_groups', to='management.farm'),
        ),
    ]
